import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Assignment-16',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <head>
    <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Bricolage+Grotesque&family=Dancing+Script&family=EB+Garamond:ital,wght@0,400;0,500;1,400;1,500&family=Montserrat:ital,wght@0,200;1,200;1,500&family=Poppins:wght@100;800&family=Roboto&family=Tilt+Prism&display=swap" rel="stylesheet"/>
    </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
